version: '3.7'

services:
  container_registry_proxy:
    image: gmarcy/container-registry-proxy:latest
    env_file: # This contains REGISTRIES and AUTH_REGISTRIES
      - ./secrets.env
    environment:
      - CACHE_MAX_SIZE=256g
      - ENABLE_MANIFEST_CACHE=true
    volumes:
      # Format: <host-path>:<container-path>; adapt to your needs
      - ./registry_proxy_mirror_cache:/registry_proxy_mirror_cache # This will be up to CACHE_MAX_SIZE big
      - ./registry_proxy_mirror_certs:/ca
    ports:
      - 0.0.0.0:3128:3128 # 0.0.0.0 binds to all interfaces
